# Site settings
title: Jeremy Books
email: jeremy.books@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  3D Modeller and Surfacing Artist
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeremybooks.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  donteatpaper

# Build settings
markdown: kramdown
